run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  staticcheck:
    checks:
      - "all"
      - "-SA1019"

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019.*aws-sdk-go.*deprecated"
